In [98]:
import pandas as pd

In [128]:
df = pd.read_csv("https://raw.githubusercontent.com/cvanmiltenburg/data-spring-2026/refs/heads/main/MTA_NYCT_Paratransit_Customer_Complaints__Beginning_February_2024_20260417.csv")
df

,Date,Provider_Type,Category,Complaints
0,02/28/2026,Non-Transportation,IT/Technology,1
1,02/28/2026,Other/Unidentified Provider,NaN,13
2,02/28/2026,Broker,Driver,3
3,02/28/2026,Primary,Vehicles,1
4,02/28/2026,Primary,Service - Ride Time,2
...,...,...,...,...
14287,02/01/2024,Broker,Service - Ride Time,3
14288,02/01/2024,Primary,Driver,2
14289,02/01/2024,Broker,Service - Other,3
14290,02/01/2024,Broker,Service - No Shows,14
14291,02/01/2024,Broker,Service - Late Pickup,4

In [129]:
# Find the number of unique providers
df["Provider_Type"].unique()

<StringArray>
[         'Non-Transportation', 'Other/Unidentified Provider',
                      'Broker',                     'Primary',
                'Supplemental',                      'E-Hail']
Length: 6, dtype: str

In [130]:
primary = df[df["Provider_Type"] == "Primary"]
broker = df[df["Provider_Type"] == "Broker"]
supplemental = df[df["Provider_Type"] == "Supplemental"]
other = df[df["Provider_Type"] == "Other/Unidentified Provider"]
ehail = df[df["Provider_Type"] == "E-Hail"]

In [131]:
# Change the date format and filter monthly complaints by provider type
primary["Date"] = pd.to_datetime(primary["Date"])

primary_monthly = (
    primary
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

primary_monthly

         Date  Complaints
0  2024-02-29         683
1  2024-03-31         818
2  2024-04-30         766
3  2024-05-31         919
4  2024-06-30         939
5  2024-07-31         753
6  2024-08-31         770
7  2024-09-30        1004
8  2024-10-31        1047
9  2024-11-30         926
10 2024-12-31         977
11 2025-01-31         735
12 2025-02-28         628
13 2025-03-31         762
14 2025-04-30         722
15 2025-05-31         908
16 2025-06-30         871
17 2025-07-31         822
18 2025-08-31         782
19 2025-09-30         996
20 2025-10-31        1182
21 2025-11-30         896
22 2025-12-31        1123
23 2026-01-31         899
24 2026-02-28         929

In [132]:
broker["Date"] = pd.to_datetime(broker["Date"])

broker_monthly = (
    broker
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

broker_monthly

         Date  Complaints
0  2024-02-29        1593
1  2024-03-31        1870
2  2024-04-30        2001
3  2024-05-31        2073
4  2024-06-30        1771
5  2024-07-31        1895
6  2024-08-31        1813
7  2024-09-30        2209
8  2024-10-31        2478
9  2024-11-30        2000
10 2024-12-31        2383
11 2025-01-31        2116
12 2025-02-28        1987
13 2025-03-31        2591
14 2025-04-30        2516
15 2025-05-31        2522
16 2025-06-30        2460
17 2025-07-31        2572
18 2025-08-31        2068
19 2025-09-30        2528
20 2025-10-31        2632
21 2025-11-30        2302
22 2025-12-31        2900
23 2026-01-31        2426
24 2026-02-28        2439

In [133]:
supplemental["Date"] = pd.to_datetime(supplemental["Date"])

supplemental_monthly = (
    supplemental
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

supplemental_monthly

         Date  Complaints
0  2024-02-29         169
1  2024-03-31         177
2  2024-04-30         198
3  2024-05-31         160
4  2024-06-30         157
5  2024-07-31         144
6  2024-08-31         164
7  2024-09-30         201
8  2024-10-31         224
9  2024-11-30         204
10 2024-12-31         279
11 2025-01-31         277
12 2025-02-28         284
13 2025-03-31         413
14 2025-04-30         424
15 2025-05-31         494
16 2025-06-30         450
17 2025-07-31         405
18 2025-08-31         363
19 2025-09-30         424
20 2025-10-31         438
21 2025-11-30         302
22 2025-12-31         354
23 2026-01-31         312
24 2026-02-28         275

In [134]:
other["Date"] = pd.to_datetime(other["Date"])

other_monthly = (
    other
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

other_monthly

         Date  Complaints
0  2024-02-29          44
1  2024-03-31          75
2  2024-04-30          75
3  2024-05-31          64
4  2024-06-30          70
5  2024-07-31          87
6  2024-08-31          65
7  2024-09-30          69
8  2024-10-31         107
9  2024-11-30          66
10 2024-12-31          66
11 2025-01-31          46
12 2025-02-28          36
13 2025-03-31          58
14 2025-04-30          54
15 2025-05-31          78
16 2025-06-30          74
17 2025-07-31          84
18 2025-08-31          70
19 2025-09-30         100
20 2025-10-31          93
21 2025-11-30         109
22 2025-12-31         108
23 2026-01-31         109
24 2026-02-28         315

In [135]:
ehail["Date"] = pd.to_datetime(ehail["Date"])

ehail["Date"] = pd.to_datetime(ehail["Date"])
ehail_monthly = (
    ehail
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

ehail_monthly

         Date  Complaints
0  2024-02-29           7
1  2024-03-31           2
2  2024-04-30           2
3  2024-05-31           8
4  2024-06-30           8
5  2024-07-31           1
6  2024-08-31           3
7  2024-09-30          12
8  2024-10-31           8
9  2024-11-30           2
10 2024-12-31           4
11 2025-01-31           7
12 2025-02-28           3
13 2025-03-31           1
14 2025-04-30           0
15 2025-05-31           1
16 2025-06-30           0
17 2025-07-31           0
18 2025-08-31           0
19 2025-09-30           0
20 2025-10-31           0
21 2025-11-30           1
22 2025-12-31           0
23 2026-01-31           1

In [136]:
# Find the number of unique complaint types
df["Category"].unique()

<StringArray>
[             'IT/Technology',                          nan,
                     'Driver',                   'Vehicles',
        'Service - Ride Time',      'Service - Late Pickup',
         'Service - No Shows', 'Travel Services (Same Day)',
      'Travel Planning (Res)',                 'Scheduling',
                     'Policy',                   'Customer',
            'Service - Other',         'Customer Relations',
                'Eligibility',                      'Other']
Length: 16, dtype: str

In [137]:
# List the complaints by the number of each complaint type
df.groupby("Category")["Complaints"].sum().sort_values(ascending=False)

Category
Driver                        31678
Service - No Shows            29069
Service - Ride Time           11898
Service - Late Pickup          9546
Policy                         8194
Customer                       7422
Travel Services (Same Day)     3401
Travel Planning (Res)          3362
Service - Other                3081
IT/Technology                  3005
Vehicles                       2085
Scheduling                     1796
Eligibility                    1399
Customer Relations              321
Other                            19
Name: Complaints, dtype: int64

In [148]:
# List the complaints by the number of each complaint type
df.groupby(["Provider_Type", "Category"])["Complaints"].sum()

Provider_Type                Category
Broker                       Driver                        22774
                             Service - Late Pickup          4969
                             Service - No Shows            17292
                             Service - Other                2437
                             Service - Ride Time            7549
                             Vehicles                       1124
E-Hail                       Driver                           42
                             Service - Late Pickup             9
                             Service - No Shows               13
                             Service - Other                   3
                             Service - Ride Time               2
                             Vehicles                          2
Non-Transportation           Customer                       7422
                             Customer Relations              321
                             Eligibility                    1399
                             IT/Technology                  3005
                             Other                            19
                             Policy                         8194
                             Scheduling                     1796
                             Travel Planning (Res)          3362
                             Travel Services (Same Day)     3401
Other/Unidentified Provider  Driver                         1091
                             Service - Late Pickup           169
                             Service - No Shows              485
                             Service - Other                 103
                             Service - Ride Time              93
                             Vehicles                         52
Primary                      Driver                         5561
                             Service - Late Pickup          3690
                             Service - No Shows             8486
                             Service - Other                 342
                             Service - Ride Time            3343
                             Vehicles                        434
Supplemental                 Driver                         2210
                             Service - Late Pickup           709
                             Service - No Shows             2793
                             Service - Other                 196
                             Service - Ride Time             911
                             Vehicles                        473
Name: Complaints, dtype: int64

In [149]:
# Sort the monthly number of complaints by by complaint type and provider type
category_monthly[category_monthly["Provider_Type"] == "Primary"].sort_values("Complaints", ascending=False)

    Provider_Type            Category       Date  Complaints
601       Primary  Service - No Shows 2025-12-31         514
599       Primary  Service - No Shows 2025-10-31         466
603       Primary  Service - No Shows 2026-02-28         436
589       Primary  Service - No Shows 2024-12-31         411
602       Primary  Service - No Shows 2026-01-31         394
..            ...                 ...        ...         ...
667       Primary            Vehicles 2025-03-31           8
664       Primary            Vehicles 2024-12-31           8
628       Primary     Service - Other 2026-02-28           8
675       Primary            Vehicles 2025-11-30           7
627       Primary     Service - Other 2026-01-31           5

[150 rows x 4 columns]

In [150]:
category_monthly[category_monthly["Provider_Type"] == "Broker"].sort_values("Complaints", ascending=False)

    Provider_Type            Category       Date  Complaints
72         Broker  Service - No Shows 2025-12-31        1174
8          Broker              Driver 2024-10-31        1086
17         Broker              Driver 2025-07-31        1055
20         Broker              Driver 2025-10-31        1052
13         Broker              Driver 2025-03-31        1048
..            ...                 ...        ...         ...
134        Broker            Vehicles 2024-11-30          31
140        Broker            Vehicles 2025-05-31          31
125        Broker            Vehicles 2024-02-29          29
127        Broker            Vehicles 2024-04-30          24
126        Broker            Vehicles 2024-03-31          20

[150 rows x 4 columns]

In [151]:
category_monthly[category_monthly["Provider_Type"] == "Supplemental"].sort_values("Complaints", ascending=False)

    Provider_Type            Category       Date  Complaints
744  Supplemental  Service - No Shows 2025-05-31         179
743  Supplemental  Service - No Shows 2025-04-30         165
742  Supplemental  Service - No Shows 2025-03-31         161
745  Supplemental  Service - No Shows 2025-06-30         155
748  Supplemental  Service - No Shows 2025-09-30         154
..            ...                 ...        ...         ...
760  Supplemental     Service - Other 2024-08-31           4
810  Supplemental            Vehicles 2024-08-31           4
811  Supplemental            Vehicles 2024-09-30           3
756  Supplemental     Service - Other 2024-04-30           2
757  Supplemental     Service - Other 2024-05-31           1

[150 rows x 4 columns]

In [152]:
category_monthly[category_monthly["Provider_Type"] == "Supplemental"].sort_values("Complaints", ascending=False)

    Provider_Type            Category       Date  Complaints
744  Supplemental  Service - No Shows 2025-05-31         179
743  Supplemental  Service - No Shows 2025-04-30         165
742  Supplemental  Service - No Shows 2025-03-31         161
745  Supplemental  Service - No Shows 2025-06-30         155
748  Supplemental  Service - No Shows 2025-09-30         154
..            ...                 ...        ...         ...
760  Supplemental     Service - Other 2024-08-31           4
810  Supplemental            Vehicles 2024-08-31           4
811  Supplemental            Vehicles 2024-09-30           3
756  Supplemental     Service - Other 2024-04-30           2
757  Supplemental     Service - Other 2024-05-31           1

[150 rows x 4 columns]

In [153]:
# Export the above data
category_monthly.to_csv("category_monthly.csv", index=False)