In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("MTA_Paratransit_Feb_24_May_26")
df

,Date,Provider_Type,Category,Complaints
0,02/01/2024,Primary,Driver,2
1,02/01/2024,Primary,Service - Late Pickup,5
2,02/01/2024,Primary,Service - No Shows,12
3,02/01/2024,Primary,Service - Ride Time,2
4,02/01/2024,Primary,Vehicles,2
...,...,...,...,...
15594,04/30/2026,Other/Unidentified Provider,Service - Late Pickup,26
15595,04/30/2026,Other/Unidentified Provider,Service - No Shows,39
15596,04/30/2026,Other/Unidentified Provider,Service - Other,8
15597,04/30/2026,Other/Unidentified Provider,Service - Ride Time,22
15598,04/30/2026,Other/Unidentified Provider,Vehicles,2

In [8]:
# Find the number of unique providers
df["Provider_Type"].unique()

<StringArray>
[                    'Primary',                      'Broker',
                'Supplemental',          'Non-Transportation',
 'Other/Unidentified Provider',                      'E-Hail']
Length: 6, dtype: str

In [45]:
# Extract month and date
## I asked Claude: "Using pandas, how can I find the total number of complaints per month from the attached dataset?"
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.to_period("M")

# Total complaints per month
monthly_totals = df.groupby("Month")["Complaints"].sum().reset_index()

monthly_totals

      Month  Complaints
0   2024-02        3219
1   2024-03        3732
2   2024-04        3893
3   2024-05        4084
4   2024-06        3704
5   2024-07        3863
6   2024-08        3715
7   2024-09        4518
8   2024-10        5117
9   2024-11        4182
10  2024-12        4856
11  2025-01        4194
12  2025-02        3860
13  2025-03        5106
14  2025-04        5101
15  2025-05        5530
16  2025-06        5249
17  2025-07        5274
18  2025-08        4652
19  2025-09        5337
20  2025-10        5795
21  2025-11        4764
22  2025-12        6023
23  2026-01        5200
24  2026-02        5378
25  2026-03        8097
26  2026-04        6686

In [50]:
### To verify, I copied the MTA data for a random month (April 2024) into a spreadsheet and summed together the daily complaints to find that there were 3983.

In [24]:
# Define each provider 
primary = df[df["Provider_Type"] == "Primary"]
broker = df[df["Provider_Type"] == "Broker"]
supplemental = df[df["Provider_Type"] == "Supplemental"]
other = df[df["Provider_Type"] == "Other/Unidentified Provider"]
ehail = df[df["Provider_Type"] == "E-Hail"]

In [47]:
# Filter monthly complaints by provider type
## I asked Claude: "How can I filter the monthly complaints by provider type (primary, broker, etc.)?

# Primary provider complaints per month
primary_monthly = (
    primary
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

primary_monthly

         Date  Complaints
0  2024-02-29         683
1  2024-03-31         818
2  2024-04-30         766
3  2024-05-31         919
4  2024-06-30         939
5  2024-07-31         753
6  2024-08-31         770
7  2024-09-30        1004
8  2024-10-31        1047
9  2024-11-30         926
10 2024-12-31         977
11 2025-01-31         735
12 2025-02-28         628
13 2025-03-31         762
14 2025-04-30         722
15 2025-05-31         908
16 2025-06-30         871
17 2025-07-31         822
18 2025-08-31         782
19 2025-09-30         996
20 2025-10-31        1182
21 2025-11-30         896
22 2025-12-31        1123
23 2026-01-31         902
24 2026-02-28         955
25 2026-03-31        1048
26 2026-04-30         841

In [49]:
### To verify, I copied the MTA data for a random month (January 2025) into a spreadsheet and used filters and a pivot table to find 735 primary provider complaints.

In [27]:
# Broker provider complaints per month
broker["Date"] = pd.to_datetime(broker["Date"])

broker_monthly = (
    broker
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

broker_monthly

         Date  Complaints
0  2024-02-29        1593
1  2024-03-31        1870
2  2024-04-30        2001
3  2024-05-31        2073
4  2024-06-30        1771
5  2024-07-31        1895
6  2024-08-31        1813
7  2024-09-30        2209
8  2024-10-31        2478
9  2024-11-30        2000
10 2024-12-31        2383
11 2025-01-31        2116
12 2025-02-28        1987
13 2025-03-31        2591
14 2025-04-30        2516
15 2025-05-31        2521
16 2025-06-30        2460
17 2025-07-31        2573
18 2025-08-31        2068
19 2025-09-30        2528
20 2025-10-31        2632
21 2025-11-30        2302
22 2025-12-31        2900
23 2026-01-31        2424
24 2026-02-28        2559
25 2026-03-31        4632
26 2026-04-30        2968

In [28]:
# Supplemental provider complaints per month
supplemental["Date"] = pd.to_datetime(supplemental["Date"])

supplemental_monthly = (
    supplemental
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

supplemental_monthly

         Date  Complaints
0  2024-02-29         169
1  2024-03-31         177
2  2024-04-30         198
3  2024-05-31         160
4  2024-06-30         157
5  2024-07-31         144
6  2024-08-31         164
7  2024-09-30         201
8  2024-10-31         224
9  2024-11-30         204
10 2024-12-31         279
11 2025-01-31         277
12 2025-02-28         284
13 2025-03-31         413
14 2025-04-30         424
15 2025-05-31         494
16 2025-06-30         450
17 2025-07-31         404
18 2025-08-31         363
19 2025-09-30         424
20 2025-10-31         436
21 2025-11-30         301
22 2025-12-31         355
23 2026-01-31         311
24 2026-02-28         282
25 2026-03-31         226
26 2026-04-30         180

In [29]:
# Other provider complaints per month
other["Date"] = pd.to_datetime(other["Date"])

other_monthly = (
    other
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

other_monthly

         Date  Complaints
0  2024-02-29          44
1  2024-03-31          75
2  2024-04-30          75
3  2024-05-31          64
4  2024-06-30          70
5  2024-07-31          87
6  2024-08-31          65
7  2024-09-30          69
8  2024-10-31         107
9  2024-11-30          66
10 2024-12-31          66
11 2025-01-31          46
12 2025-02-28          36
13 2025-03-31          58
14 2025-04-30          54
15 2025-05-31          78
16 2025-06-30          74
17 2025-07-31          83
18 2025-08-31          70
19 2025-09-30         100
20 2025-10-31          93
21 2025-11-30         109
22 2025-12-31         107
23 2026-01-31         105
24 2026-02-28         132
25 2026-03-31         354
26 2026-04-30         824

In [30]:
# Ehail provider complaints per month
ehail["Date"] = pd.to_datetime(ehail["Date"])

ehail["Date"] = pd.to_datetime(ehail["Date"])
ehail_monthly = (
    ehail
    .groupby(pd.Grouper(key="Date", freq="ME"))["Complaints"]
    .sum()
    .reset_index()
)

ehail_monthly

         Date  Complaints
0  2024-02-29           7
1  2024-03-31           2
2  2024-04-30           2
3  2024-05-31           8
4  2024-06-30           8
5  2024-07-31           1
6  2024-08-31           3
7  2024-09-30          12
8  2024-10-31           8
9  2024-11-30           2
10 2024-12-31           4
11 2025-01-31           7
12 2025-02-28           3
13 2025-03-31           1
14 2025-04-30           0
15 2025-05-31           1
16 2025-06-30           0
17 2025-07-31           0
18 2025-08-31           0
19 2025-09-30           0
20 2025-10-31           0
21 2025-11-30           1
22 2025-12-31           0
23 2026-01-31           1
24 2026-02-28           0
25 2026-03-31           8
26 2026-04-30           1

In [31]:
# Find the number of unique complaint types
df["Category"].unique()

<StringArray>
[                    'Driver',      'Service - Late Pickup',
         'Service - No Shows',        'Service - Ride Time',
                   'Vehicles',            'Service - Other',
                   'Customer',         'Customer Relations',
                'Eligibility',              'IT/Technology',
                     'Policy',      'Travel Planning (Res)',
 'Travel Services (Same Day)',                 'Scheduling',
                          nan,                      'Other']
Length: 16, dtype: str

In [32]:
# List the complaints by the number of each complaint type
df.groupby("Category")["Complaints"].sum().sort_values(ascending=False)

Category
Driver                        34838
Service - No Shows            33852
Service - Ride Time           12762
Service - Late Pickup         11055
Customer                       9152
Policy                         9040
Travel Services (Same Day)     3775
Travel Planning (Res)          3650
Service - Other                3589
IT/Technology                  3206
Vehicles                       2290
Scheduling                     1894
Eligibility                    1504
Customer Relations              350
Other                            28
Name: Complaints, dtype: int64

In [33]:
# List the complaints by the number of each complaint type
df.groupby(["Provider_Type", "Category"])["Complaints"].sum()

Provider_Type                Category
Broker                       Driver                        24876
                             Service - Late Pickup          6066
                             Service - No Shows            20795
                             Service - Other                2855
                             Service - Ride Time            8034
                             Vehicles                       1237
E-Hail                       Driver                           47
                             Service - Late Pickup             9
                             Service - No Shows               17
                             Service - Other                   3
                             Service - Ride Time               2
                             Vehicles                          2
Non-Transportation           Customer                       9152
                             Customer Relations              350
                             Eligibility                    1504
                             IT/Technology                  3206
                             Other                            28
                             Policy                         9040
                             Scheduling                     1894
                             Travel Planning (Res)          3650
                             Travel Services (Same Day)     3775
Other/Unidentified Provider  Driver                         1474
                             Service - Late Pickup           296
                             Service - No Shows              787
                             Service - Other                 162
                             Service - Ride Time             174
                             Vehicles                         74
Primary                      Driver                         6100
                             Service - Late Pickup          3946
                             Service - No Shows             9288
                             Service - Other                 363
                             Service - Ride Time            3599
                             Vehicles                        479
Supplemental                 Driver                         2341
                             Service - Late Pickup           738
                             Service - No Shows             2965
                             Service - Other                 206
                             Service - Ride Time             953
                             Vehicles                        498
Name: Complaints, dtype: int64

In [38]:
# Group and count complaints by month
## I asked Claude: "How can I sort the number of monthly complaints by both complaint type and provider type?"

# First, group complaints by month 
category_monthly = (
    df.groupby(["Month", "Category", "Provider_Type"])
    .size()
    .reset_index(name="Complaints")
)

# Filter the monthly complaints to obtain primary provider complaints
category_monthly[category_monthly["Provider_Type"] == "Primary"].sort_values("Complaints", ascending=False)

       Month             Category Provider_Type  Complaints
601  2025-08               Driver       Primary          29
105  2024-05               Driver       Primary          28
491  2025-04  Service - Ride Time       Primary          28
502  2025-05               Driver       Primary          28
834  2026-03               Driver       Primary          28
..       ...                  ...           ...         ...
817  2026-02      Service - Other       Primary           6
886  2026-04      Service - Other       Primary           6
465  2025-03             Vehicles       Primary           5
784  2026-01      Service - Other       Primary           5
727  2025-11             Vehicles       Primary           5

[162 rows x 4 columns]

In [41]:
### To verify, I located a random entry from this sampling (Vehicles - Primary - March 2025) in the raw CSV file and found there were 5 complaints.

In [42]:
# Broker provider complaints
category_monthly[category_monthly["Provider_Type"] == "Broker"].sort_values("Complaints", ascending=False)

       Month  Category Provider_Type  Complaints
764  2026-01    Driver        Broker          31
437  2025-03    Driver        Broker          31
566  2025-07    Driver        Broker          31
339  2024-12    Driver        Broker          31
831  2026-03    Driver        Broker          31
..       ...       ...           ...         ...
30   2024-02  Vehicles        Broker          15
96   2024-04  Vehicles        Broker          15
725  2025-11  Vehicles        Broker          14
63   2024-03  Vehicles        Broker          14
526  2025-05  Vehicles        Broker          14

[162 rows x 4 columns]

In [43]:
# Supplemental provider complaints
category_monthly[category_monthly["Provider_Type"] == "Supplemental"].sort_values("Complaints", ascending=False)

       Month            Category Provider_Type  Complaints
440  2025-03              Driver  Supplemental          28
667  2025-10              Driver  Supplemental          28
747  2025-12  Service - No Shows  Supplemental          27
680  2025-10  Service - No Shows  Supplemental          26
515  2025-05  Service - No Shows  Supplemental          26
..       ...                 ...           ...         ...
234  2024-08            Vehicles  Supplemental           4
887  2026-04     Service - Other  Supplemental           3
268  2024-09            Vehicles  Supplemental           3
90   2024-04     Service - Other  Supplemental           2
124  2024-05     Service - Other  Supplemental           1

[162 rows x 4 columns]

In [51]:
# Export the above data
category_monthly.to_csv("category_monthly.csv", index=False)