In [1]:
##import pandas
import pandas as pd

In [6]:
## read diamonds into a df
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")

df

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
## type df

type(df)

pandas.DataFrame

In [10]:
## call the top only
## returns first 5

df.head()

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [12]:
## call the last 5

df.tail()

       carat diamond cut color clarity  depth  table  price     x     y     z
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [14]:
## sample of n
df.sample(10)

       carat diamond cut color clarity  depth  table  price     x     y     z
5328    0.90       Ideal     E     SI2   62.6   57.0   3808  6.13  6.20  3.86
21057   0.31       Ideal     F     VS2   62.3   55.0    625  4.35  4.38  2.72
18539   1.21     Premium     H     VS1   62.5   59.0   7555  6.80  6.74  4.23
43074   0.60   Very Good     H     SI1   60.4   63.0   1378  5.45  5.41  3.28
6241    0.90       Ideal     D     SI2   62.4   56.0   4007  6.24  6.16  3.87
7708    0.90        Good     E     VS2   64.0   58.0   4278  6.02  6.07  3.87
21924   1.23   Very Good     G    VVS2   62.2   57.0   9999  6.80  6.87  4.25
9540    1.13     Premium     H     SI2   61.1   59.0   4619  6.73  6.65  4.09
36970   0.39   Very Good     E    VVS2   62.2   55.0    962  4.66  4.70  2.91
15773   1.03     Premium     F     VS2   62.4   58.0   6307  6.47  6.42  4.02

In [15]:
##get basic overview of the data
## float = decimal point number

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   carat        53940 non-null  float64
 1   diamond cut  53940 non-null  str
 2   color        53940 non-null  str
 3   clarity      53940 non-null  str
 4   depth        53940 non-null  float64
 5   table        53940 non-null  float64
 6   price        53940 non-null  int64
 7   x            53940 non-null  float64
 8   y            53940 non-null  float64
 9   z            53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

In [16]:
## non-null means there is no missing data in that row
## float64 means the integer has 64 points of data

In [17]:
## a list is a single column in excel/sheets
## a list of dictionaries (data frame) is tabular data -- multiple columns in a spreadsheet
## a series is a one-dimensional array of data

In [18]:
## call the series carat
df.carat

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [19]:
## what type of data? 
type(df.carat)

pandas.Series

In [23]:
## multiply carat series by 2
(df.carat)*2

0        0.46
1        0.42
2        0.46
3        0.58
4        0.62
         ...
53935    1.44
53936    1.44
53937    1.40
53938    1.72
53939    1.50
Name: carat, Length: 53940, dtype: float64

In [24]:
df.color

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: str

In [28]:
## call the diamond cut series
df["diamond cut"]
## need square brackets because of the space in the dictionary

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: diamond cut, Length: 53940, dtype: str

In [29]:
df.head()

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [31]:
## What are the unique values of "diamond cut"?
df["diamond cut"].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [32]:
## how many unique diamond cut values?
df["diamond cut"].nunique()

5